name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true   # ✅ allow deprecated Node.js

jobs:

  # security-scan:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
  #       with:
  #         scan-type: fs
  #         scan-ref: .
  #         format: table
  #         exit-code: 1   # 
  #         vuln-type: os,library
  #         severity: HIGH,CRITICAL
  
  build-test-analyze:
    # needs: security-scan
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      # - name: Run Jest tests with coverage
      #   run: npm test -- --coverage

      # - name: Upload coverage artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-report
      #     path: coverage/lcov.info

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarqube-scan-action@v5.0.0 # Or current stable SHA update
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.host.url=https://sonarcloud.io
      #       -Dsonar.projectKey=md-sadidtahsin_assignment-14-final
      #       -Dsonar.organization=md-sadidtahsin
      #       -Dsonar.sources=src
      #       -Dsonar.exclusions=**/node_modules/**
      #       -Dsonar.test.inclusions=tests/**/*.test.js
      #       -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      #       -Dsonar.qualitygate.wait=true
      
      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Run OPA Docker policy check
        run: |
          opa eval --data policy.rego --input input-data.json "data.policy"
